BIP-CTV: fix mistypes, omissions, etc
JeremyRubin/bips pull request #4
Opened 2019-12-14 08:02 UTC by dgpv

The fixes for issues spotted after first read

2019-12-14 08:04 UTC, dgpv commented
Note that in "====NOP-Default and Standardness Rules====" I changed the `exact match for a 32-byte previously pushed value` to `If the argument length is not exactly 32`, because as I understand, it refers to the rule in Summary "The element on the stack is 32 bytes long, NOP otherwise"

2019-12-17 07:14 UTC, JeremyRubin requested changes
Thanks!

I swear you can read something hundreds of times and miss the same little errors :)

2019-12-17 07:14 UTC, JeremyRubin commented on bip-ctv.mediawiki
> +be spent at the different index. This makes it safer to design wallet vault contracts without half-spend
Actually same is correct here.

if you want to make this one more clear it should read "they cannot both be spent at the same index, which implies that they cannot be spent in the same transaction."

2019-12-17 07:42 UTC, dgpv commented
I rephrased the paragraph about the same index. please check.

2019-12-17 07:43 UTC, dgpv commented on bip-ctv.mediawiki
> +This makes it safer to design wallet vault contracts without half-spend vulnerabilities.
Rephrased.

2019-12-17 08:39 UTC, merged

2019-12-17 08:40 UTC, JeremyRubin commented
Thanks :)